gantt
    title 无线开发时间进度
    dateFormat  YYYY-MM-DD

    section 其他项目插入
    PC阅读页优化 :done, b1, 2015-09-19, 4d
    PC法律专区新增模块: done, b2, 2015-10-16, 1d


    section 开发进度
    熟悉开发环境，梳理主站功能点和需要的接口:done, a1, 2015-09-10, 4d
    首页、排行、分类部分迁移:done, a2, after a1, 5d
    专题、pgc和ugc个人主页迁移:done, a3, after b1, 4d
    调研xpage本地文件推送到nhost集群的解决方案:done, a4, after a3, 2d
